version: "3"

services:
    mongo:
        image: mongo:4.1
        container_name: colonel
        ports:
            - "27017:27017"
    
    user:
        build:
          context: "./Colonel.User"
        depends_on:
            - "mongo"
        ports:
            - "5005:5005"

    product:
        build:
            context: "./Colonel.Product"
        depends_on:
            - "mongo"
        ports:
            - "5003:5003"      

    price:
        build:
          context: "./Colonel.Price"
        depends_on:
            - "mongo"
        ports:
            - "5001:5001"
        links: 
            - mongo
            
    stock:
        build:
           context: "./Colonel.Stock"
        depends_on:
           - "mongo"
        ports:
            - "5002:5002"

    shopping:
        build:
            context: "./Colonel.Shopping"
        depends_on:
            - "mongo"
            - "product"
            - "price"
            - "user"
            - "stock"
        ports:
            - "5004:5004"
        links: 
            - "mongo"
            - "product"
            - "price"
            - "user"
            - "stock"